package nbu.medicaljournal.model;

public enum Speciality {
    IMMUNOLOGIST,
    ANESTHESIOLOGIST,
    CARDIOLOGIST,
    COLON_AND_RECTAL_SURGEON,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    EMERGENCY_MEDICINE_SPECIALIST,
    FAMILY_PHYSICIAN,
    GASTROENTEROLOGIST,
    HEMATOLOGIST,
    INTERNIST,
    ONCOLOGIST,
    OPHTHALMOLOGIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    PLASTIC_SURGEON,
    RADIOLOGIST,
    UROLOGIST,
    GENERAL_SURGEON,
    INTERN
}